### ISSUE TITLE
Titles and Meta Descriptions

### ISSUE THREAD

**Issue by PhilJ88** [csu/singularity-cms#4]
Many thanks for Singularity... it's really helped me a lot.

For correct display of title tags, I had to replace...

```<title><?php (ucwords(strtolower($url))) ? ucwords(strtolower($url)) : $default_title; ?></title>```

With...

```<title><?php echo (ucwords(strtolower($url))) ? ucwords(strtolower($url)) : $default_title; ?></title>```

Any thoughts on displaying dynamic meta _description_ tags for each page also?

**Comment by csu** [comment]
Fixed the title, thanks! As for meta tags, that would be possible, but where would be best to get that data from? Currently, none of the page text files require any additional metadata. I suppose we could allow for optional YAML front matter?

**Comment by PhilJ88** [comment]
Yes, not too sure... I had a play around with it, but took out the Strapdown stuff, and used .php as the $file_format ...

http://www.xcms.co.uk/singularity/
d/l - http://www.xcms.co.uk/singularity/singularity_test_v1.zip

Maybe there's an alternative way to display the $content instead of echoing it... then custom meta descriptions might be possible (?).

I added a menu, breadcrumbs and tested a subfolder (/store).

It's a great little script you've made.

**Comment by PhilJ88** [comment]
ok, made some changes, it now includes the page content instead of echoing it, and I got custom titles / descriptions working...

http://www.xcms.co.uk/singularity/about-us
d/l - http://www.xcms.co.uk/singularity/singularity_test_v2.zip

So in your pages you can add at the top...

&lt;?php
$page_title = &quot;Custom Title&quot;;
$page_description = &quot;Custom Description&quot;;
?&gt;
